name: Bug report
description: File a bug
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes: {label: What happened?, description: Include exact commands/prompts.}
    validations: {required: true}
  - type: input
    id: version
    attributes: {label: Version, placeholder: v1.2.0}

