name: JSON lint
on:
  push:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate JSON
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          jq -e . compression-menu.json > /dev/null
          if [ -d examples ]; then
            find examples -name "*.json" -print0 | xargs -0 -I{} jq -e . "{}" > /dev/null
          fi


